### ISSUE TITLE
old google Drive link

### ISSUE THREAD

**Issue by lechk82** [deepdetail/mqlinux#1]
Your Link https://drive.google.com/file/d/1Ws2IUiCGSKKQ2dCM5XJBV-pog-hk17PM/view?usp=sharing
provides the old release (MQLinux-ARM-19.02Beta1.for-mtk-bpi-r2-SD.img) instead of Beta 3.

**Comment by deepdetail** [comment]
In fact, it is the version of Beta3, just ignore the filename.
If the file name changes, it will cause the share link to be changed, so I am. . . a little lazy

**Comment by deepdetail** [comment]
Now Beta4 is released, use the different link addr.
